nameGenerator:
  prefix: local-
  suffix:
    valueFrom:
      envVariable: GLOBAL_CUSTOM_DEPLOYMENT_NAME_IDENTIFIER
toolchainRegion: us-east-1
groups:
  - name: networking
    path: manifests/local-isolated/networking-modules.yaml
  - name: storage
    path: manifests/local-isolated/storage-modules.yaml
  - name: replication
    path: manifests/local-isolated/replicator-modules.yaml
  - name: compute
    path: manifests/local-isolated/compute-modules.yaml
  - name: containers
    path: manifests/local-isolated/containers-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true
