name: examples-iso
toolchainRegion: us-east-1
groups:
  - name: simple
    path: manifests/isolated/example-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    parametersGlobal:
      myTestGlobalParam: HeyHereIAmGlobal
    regionMappings:
      - region: us-east-1
        default: true
        parametersRegional:
          dockerCredentialsSecret: aws-idf-docker-credentials
          vpcId: vpc-XXXXXXXXX
          publicSubnetIds:
            - subnet-XXXXXXXXX
            - subnet-XXXXXXXXX
          privateSubnetIds:
            - subnet-XXXXXXXXX
            - subnet-XXXXXXXXX
          isolatedSubnetIds:
            - subnet-XXXXXXXXX
            - subnet-XXXXXXXXX
          securityGroupIds:
            - sg-XXXXXXXXX
          myTestRegionParam: HeyHereIAmRegional
        network:
          vpcId:
            valueFrom:
              parameterValue: vpcId
          privateSubnetIds:
            valueFrom:
              parameterValue: privateSubnetIds
          securityGroupIds:
            valueFrom:
              parameterValue: securityGroupIds
      - region: us-east-2
  - alias: secondary
    accountId:
      valueFrom:
        envVariable: SECONDARY_ACCOUNT
    default: false
    regionMappings:
      - region: us-west-2
      - region: us-east-2
        default: true
