name: buckets
path: git::https://github.com/awslabs/seedfarmer-modules.git//modules/storage/buckets
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: encryption-type
    value: SSE
---
name: dummy
path: git::https://github.com/awslabs/seedfarmer-modules.git//modules/dummy/blank
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: testingRegionParams
    valueFrom:
      parameterValue: myTestRegionParam
  - name: testingGlobalParams
    valueFrom:
      parameterValue: myTestGlobalParam
