name: Generate Module Metadata

on:
  push:
    branches: ["release/**"]

  workflow_dispatch:
    inputs:
      version:
        description: 'Version of codebase to generate metadata for, x.y.z'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Generate Metadata
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Version ➕
        run: |
          if [ -z ${{ github.event.inputs.version }} ]; then echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV; else echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV; fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-2
      - name: Generate Metadata
        run: |
          python -m pip install --upgrade pip
          pip install argparse boto3
          python scripts/generate-module-metadata.py -v ${RELEASE_VERSION} -n ${{ github.event.repository.name }} -b ${{ secrets.BUCKET_NAME }}
